### ISSUE TITLE
階層的なtypeを自分で定義したい

### ISSUE THREAD

**Issue by Kanazawanaoaki** [jsk-ros-pkg/jsk_planning#102]
pddl-actionのparametersにおいて，objectというtypeは他のどのtypeでも入れることができる階層的なtypeの上位type？になっているように思います．
行いたいこととしては，同じようにingredientのtypeの下位typeとしてmixstureのtypeがあるというような階層的なtypeの定義することで，mixstureのみを対象とするpddl-actionのparameterとmixstureも含むingredient全体を対象するparameterの両方を定義可能にしたいです．
このようなことは現状の実装でも実現可能でしょうか？

#### 実現したいことの 詳細な説明
問題が整理しきていなくて恐縮なのですが，
https://github.com/Kanazawanaoaki/jsk_demos/blob/not-mixutre-bad-sample/jsk_2023_09_cook_from_recipe/euslisp/pddl_test/cooking-pddl-domain.l
のように，調理用のpddl domainを定義して，
https://github.com/Kanazawanaoaki/jsk_demos/blob/not-mixutre-bad-sample/jsk_2023_09_cook_from_recipe/euslisp/pddl_test/solve-scrambled-egg.l
のようにそれぞれのproblemを定義して解いてみていっています．  

その中で，複数の食材を混ぜ合わせて新しい食材にする[mixのpddl-action](https://github.com/Kanazawanaoaki/jsk_demos/blob/65490f9da47eb85bba7f47ce730f0b65faaf6439/jsk_2023_09_cook_from_recipe/euslisp/pddl_test/cooking-pddl-domain.l#L159-L175 )を定義して，?MIXTURE変数で表される新しい食材を生成できるようにしています． その結果，pourやtransferをして欲しいところなどで，mixにより新しい食材(ingredient)を生成し，それを何度か使うことで辻褄をあわせるというハックが生まれてしまいました．  

それを防ぐために，mixにより生成される?MIXTUREはingredientではなくmixstureという別のtypeにすることによりこの問題を回避しようとしましたが，そうすると，heatなどの他のpddl-actionにおいてmixstureとingredientの両方をparameterにしたいが，やる方法がわからないという問題が発生しました．
その他にもコストをちゃんと導入するなど解決策はあるのかと思いますが，

#### 現状の実行結果
solve-scrambled-egg.lの実行結果，pourしてボウルに塩を移して欲しいところに(mix salt egg milk bowl whisk kitchen rarm)をしてしまっている．
```
(move-to stove kitchen)
(hold milk rarm kitchen)
(pour milk bowl rarm kitchen)
(place milk rarm kitchen)
(hold whisk rarm kitchen)
(mix salt egg milk bowl whisk kitchen rarm)
(hold milk rarm kitchen)
(pour milk bowl rarm kitchen)
(mix egg milk salt bowl whisk kitchen rarm)
(pour milk bowl rarm kitchen)
(mix egg-mixture egg milk bowl whisk kitchen rarm)
(place whisk rarm kitchen)
(move-to kitchen stove)
(hold small-bowl rarm stove)
(transfer butter small-bowl frying-pan rarm stove)
(place small-bowl rarm stove)
(turn-on-stove)
(heat butter melted)
(pour milk frying-pan rarm stove)
(hold wooden-spatula rarm stove)
(turn-off-stove middle)
(mix egg-mixture milk butter frying-pan wooden-spatula stove rarm)
(move-to stove kitchen)
(hold bowl rarm kitchen)
(move-to kitchen stove)
(place bowl rarm stove)
(turn-on-stove)
(heat egg-mixture surroundings-hardened)
(stir-fry egg-mixture frying-pan wooden-spatula whole-mixture-tender stove rarm)
(place wooden-spatula rarm stove)
(turn-off-stove middle)
```

**Comment by Naoki-Hiraoka** [comment]
https://www.cs.cmu.edu/~mmv/planning/readings/98aips-PDDL.pdf より引用

> All domains include a few built-in types, such as **object** (any object), and **number**.

> A typed list is used to declare the types of a list of entities; the types are preceded by a minus sign ("-"), and every other elements of the list is declared to be of the first type that follows it, or **object** if there are no types that follow it.

**Comment by Kanazawanaoaki** [comment]
@Naoki-Hiraoka 
ありがとうございます！！！
objectやnumberはbuilt-in typeだったんですね．
https://github.com/Kanazawanaoaki/jsk_demos/blob/d9779df2fb83ab33cb184f156d6488a39e845b09/jsk_2023_09_cook_from_recipe/euslisp/pddl_test/hierarchy_type_test/tmp-mix-mixture-hierarchy.l#L38-L40
```
(send *domain* :types '(ingredient vessel tool  - object
                                   mixture - ingredient
                                   state))
```
のようにすることで階層的なtypeをeus-pddlでも定義できました．  

(最初にタイポしていたために上手く行くことに気が付かず，色々試していたのですが，objectを2つのtypeで定義するという作戦も有効でした．)
