### ISSUE TITLE
could I get an example of usage of the pddl_planner node?

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_planning#37]
```
My question is: could I get an example of usage of the pddl_planner node? My own attempts
to use it via commands like "rostopic pub" are met with error messages as I am probably 
doing it incorrectly. I also wonder if you could tell me about getting a plan from the
 "downward" package directly. It seems to be better fitted to a command-line interface,
 but I don't know the complete structure of the command. Some I've deduced from "pddl.py"
 in pddl_planner - like the structure "rosrun downward plan [domain] [problem] [search options]"
 - but what are the search options? Nothing I've tried works. 
```

**Comment by k-okada** [comment]
ok, I create document for boht how to use downward program and also how to use htem as ros node, see https://github.com/jsk-ros-pkg/jsk_planning/blob/master/pddl/pddl_planner/README.md

**Comment by Grollo** [comment]
That is helpful I understand more of the basic structure now. The bare downward example isn't working for me however. I run the commands:

roscd pddl_planner/demos/sample-pddl/
rosrun downward plan sample-domain.pddl ./sample-problem.pddl

and get the following output:

1. Running translator
Second argument is a file name: use two translator arguments.
time: elapsed.time: Permission denied

Then it exits. What is happening here?

**Comment by furushchev** [comment]
@Grollo Where did you execute `rosrun` command?
downward planner calculates how long it took to generate plan and save the result to current working directory.
I suspect you executed on read only directory.
So please re-run the command like below:

```bash
cd ~
PDDL_DIR="`rospack find pddl_planner`/demos/sample-pddl"
rosrun downward plan $PDDL_DIR/sample-domain.pddl $PDDL_DIR/sample-problem.pddl
```

**Comment by Grollo** [comment]
Yes, it was a read-only folder. 
Using those commands exactly instead gives me:

1 . Running translator
Second argument is a file name: use two translator arguments.
Parsing...
Parsing: [0.000s CPU, 0.001s wall-clock]
Normalizing task... [0.000s CPU, 0.000s wall-clock]
Instantiating...
Generating Datalog program... Traceback (most recent call last):
  File "/opt/ros/indigo/share/downward/src/translate/translate.py", line 677, in <module>
    main()
  File "/opt/ros/indigo/share/downward/src/translate/translate.py", line 667, in main
    sas_task = pddl_to_sas(task)
  File "/opt/ros/indigo/share/downward/src/translate/translate.py", line 499, in pddl_to_sas
    reachable_action_params) = instantiate.explore(task)
  File "/opt/ros/indigo/share/downward/src/translate/instantiate.py", line 74, in explore
    prog = pddl_to_prolog.translate(task)
  File "/opt/ros/indigo/share/downward/src/translate/pddl_to_prolog.py", line 160, in translate
    translate_facts(prog, task)
  File "/opt/ros/indigo/share/downward/src/translate/pddl_to_prolog.py", line 150, in translate_facts
    translate_typed_object(prog, obj, type_dict)
  File "/opt/ros/indigo/share/downward/src/translate/pddl_to_prolog.py", line 143, in translate_typed_object
    supertypes = type_dict[obj.type_name].supertype_names
KeyError: 'obj'

Copying the pddl files to my home folder and running from there gives me the same error. The odd thing is, other pddl files gives different errors. Trying downward/benchmarks/gripper/prob01 gives me:

(...)
3 . Running search
This is a unit task.
usage: 
/opt/ros/indigo/share/downward/src/search/downward-release [OPTIONS] --search SEARCH < OUTPUT

* SEARCH (SearchEngine): configuration of the search algorithm
* OUTPUT (filename): preprocessor output

Options:
--help [NAME]
    Prints help for all heuristics, openlists, etc. called NAME.
    Without parameter: prints help for everything available
--landmarks LANDMARKS_PREDEFINITION
    Predefines a set of landmarks that can afterwards be referenced
    by the name that is specified in the definition.
--heuristic HEURISTIC_PREDEFINITION
    Predefines a heuristic that can afterwards be referenced
    by the name that is specified in the definition.
--random-seed SEED
    Use random seed SEED

--plan-file FILENAME
    Plan will be output to a file called FILENAME

See http://www.fast-downward.org/ for details.
Usage error occurred.
Peak memory: 3196 KB

What is notable is that both gripper/prob01 and sample-pddl works with ff and ffha, only downward is not working.

**Comment by furushchev** [comment]
@Grollo There are 3 errors

> Generating Datalog program... Traceback (most recent call last):
File "/opt/ros/indigo/share/downward/src/translate/translate.py", line 677, in 
main()
File "/opt/ros/indigo/share/downward/src/translate/translate.py", line 667, in main
sas_task = pddl_to_sas(task)
File "/opt/ros/indigo/share/downward/src/translate/translate.py", line 499, in pddl_to_sas
reachable_action_params) = instantiate.explore(task)
File "/opt/ros/indigo/share/downward/src/translate/instantiate.py", line 74, in explore
prog = pddl_to_prolog.translate(task)
File "/opt/ros/indigo/share/downward/src/translate/pddl_to_prolog.py", line 160, in translate
translate_facts(prog, task)
File "/opt/ros/indigo/share/downward/src/translate/pddl_to_prolog.py", line 150, in translate_facts
translate_typed_object(prog, obj, type_dict)
File "/opt/ros/indigo/share/downward/src/translate/pddl_to_prolog.py", line 143, in translate_typed_object
supertypes = type_dict[obj.type_name].supertype_names
KeyError: 'obj'

On my environment, this error is not reproduced, maybe wrong file name or file collapsed?
Could you re-download pddl files, and try again?

> 3 . Running search
This is a unit task.
usage: 
/opt/ros/indigo/share/downward/src/search/downward-release [OPTIONS] --search SEARCH < OUTPUT

When planning with downward, we must specify search option.

> --plan-file FILENAME
Plan will be output to a file called FILENAME

And also we must specify output file path that planner writes solution on.

e.g. `rosrun downward plan $PDDL_DIR/sample-domain.pddl $PDDL_DIR/sample-problem.pddl ipc seq-sat-lama-2011 --plan-file sample.plan`

we can see planning solution:

```bash
$ less sample.plan.1
(unstack c a)
(putdown c)
(pickup b)
(stack b c)
(pickup a)
(stack a b)
```

**Comment by k-okada** [comment]
> KeyError: 'obj'

I have fixed this just a few days ago, please try with latest source code,
https://github.com/jsk-ros-pkg/jsk_planning/commit/845d15f8e0c5acc5820b9387e778e8bd0c896a96

--
◉ Kei Okada

**Comment by Grollo** [comment]
Thank you, now it works. I'm wondering one thing though. If it is required to specify search option and solution file path when using downward, why is that not listed in "bare example" in the README?

**Comment by k-okada** [comment]
Oh, I just forgot them, please update README and send us Pull Request.


--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada This issue is solved in https://github.com/jsk-ros-pkg/jsk_planning/pull/38, and I think it's ok to close it.

**Comment by k-okada** [comment]
I'll close this issue for now, please feel free to reopen this if you still have problem.
