### ISSUE TITLE
Release request for melodic

### ISSUE THREAD

**Issue by sktometometo** [jsk-ros-pkg/jsk_planning#71]
jsk_planning is not currently released in melodic.

**Comment by k-okada** [comment]
please update .travis.yml for melodic/kinetic

**Comment by sktometometo** [comment]
Add melodic test: https://github.com/jsk-ros-pkg/jsk_planning/pull/72

**Comment by k-okada** [comment]
released https://github.com/ros/rosdistro/pull/24310
